---
- name: Accept Steam License
  debconf:
    name: "steam"
    question: "steam/question"
    value: "I AGREE"
    vtype: "select"

- name: Steam License Note
  debconf:
    name: "steam"
    question: "steam/license"
    value: ""
    vtype: "select"

- name: Add Multiverse Repo
  apt_repository:
    repo: deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }} multiverse
    state: present
    update_cache: no

- name: Refresh Repo
  apt:
    update_cache: yes

- name: Set 32-bit Architecture
  shell:
    cmd: |
      dpkg --add-architecture i386

- name: Install Required Packages
  apt:
    pkg:
      - lib32gcc-s1
      - tmux
      - screen
      - steamcmd
    state: present
  
- name: Create Steam Group
  group: 
    name: steam

- name: Create Steam User
  user:
    name: steam
    group: steam

- name: Create Required Directories
  file:
    path: "{{ item }}"
    state: directory
    owner: steam
    group: steam
    mode: 0777
  loop:
    - /steam/morpheus
    - /steam/server
    - ~/.steam/sdk64

- name: Symlink Steam Client
  file:
    src: ../steamcmd/linux64/steamclient.so
    dest: ~/.steam/sdk64
    state: link
    owner: steam
    group: steam
    mode: 0777