---
  GAME_PATH: "{{ morpheus['customOptions']['gamePath'] }}"

  #SERVERID: '2394010'
  SERVERID: "{{ morpheus['customOptions']['steamAppId'] }}"

  STEAMPORT: "{{ morpheus['customOptions']['steamPort'] }}"

  INSTANCEID: "{{ morpheus['instance']['id'] }}"