---
  - set_fact:
      BACKUP: "{{ NEWBACKUP }}"
    when: BACKUP == "New"

  - name: Print BACKUP
    debug:
      msg: "{{ BACKUP }}"

  - name: Install Required Packages
    package:
      name:
        - nfs-common
      state: present

  - name: Create Backup Directory
    file:
      path: '/backups/{{ BACKUP }}'
      state: directory
      owner: steam
      group: steam
      mode: 0644

  - name: Get Option List
    uri:
      method: GET
      url: "{{ MORPHURL }}api/library/option-type-lists/{{ OPTIONLIST }}"
      headers:
        Authorization: "BEARER {{ MORPHTOKEN }}"
    register: OLDATA

  - name: Print OLDATA
    debug:
      msg: '{{ OLDATA.json.optionTypeList.initialDataset }}'

  - name: Create JSON Var
    shell: |
      echo '{{ OLDATA }}' | jq .json.optionTypeList.initialDataset -r
    register: JSON

  - name: Update Dataset
    json_patch:
      src: '{{ JSON }}'
      operations:
        - op: add
          path: "/{{ BACKUP }}"
          value: "{{ JSON }}"
      pretty: yes
      create: yes

  - name: Update Option List
    uri:
      method: PUT
      body_format: json
      url: "{{ MORPHURL }}api/library/option-type-lists/{{ OPTIONLIST }}"
      headers:
        Authorization: "BEARER {{ MORPHTOKEN }}"
      body: |
        '"optionTypeList": {
          "initialDataset": {{ JSON }}
        }'


  # - name: Update Option List Values
  #   shell:
  #     cmd: |
  #       JSON=$(curl -X GET {{ MORPHURL }}api/library/option-type-lists/{{ OPTIONLIST }} --header 'content-type: application/json' --header "authorization: Bearer {{ MORPHTOKEN }}")
  #       UPDATEDJSON=$(echo $JSON | jq .optionTypeList.initialDataset)
  #       UPDATEDJSON=$(echo ${UPDATEDJSON::-6},\\r\\n {\\\"name\\\":\\\"{{ NEWBACKUP }}\\\", \\\"value\\\":\\\"{{ NEWBACKUP }}\\\"}\\r\\n]\")
  #       JS=$(echo $JSON | jq ".optionTypeList.initialDataset = $UPDATEDJSON")
  #       JS=$(echo $JS | jq 'del(.optionTypeList.id)')

  #       curl -X PUT {{ MORPHURL }}api/library/option-type-lists/{{ OPTIONLIST }} --header 'content-type: application/json' --header "authorization: Bearer {{ MORPHTOKEN }}" --data "$JS"
  
  #   when: BACKUP == 'New'

  # - name: Update Backup Job Targets
  #   shell:
  #     cmd: |
  #       JSON=$(curl -X GET {{ MORPHURL }}api/jobs/{{ JOB }} --header 'content-type: application/json' --header "authorization: Bearer {{ MORPHTOKEN }}")
  #       UPDATEDJSON=$(echo $JSON | jq .job.targets)
  #       UPDATEDJSON=$(echo ${UPDATEDJSON::-1}, {\"refId\": $INSTANCEID}])
  #       JS=$(echo $JSON | jq ".job.targets = $UPDATEDJSON")

  #       curl -X PUT {{ MORPHURL }}api/jobs/{{ JOB }} --header 'content-type: application/json' --header "authorization: Bearer {{ MORPHTOKEN }}" --data "$JS"