---
  - set_fact:
      BACKUP: "{{ NEWBACKUP }}"
    when: BACKUP == "New"

  - name: Install Required Packages
    package:
      name:
        - nfs-common
      state: present

  - name: Create Backup Directory
    file:
      path: '/backups/{{ BACKUP }}'
      state: directory
      owner: steam
      group: steam
      mode: 0644

  - name: Mount NFS Share
    ansible.posix.mount:
      path: /backups
      src: "{{ NFS }}"
      fstype: nfs
      state: mounted
      opts: "nfsvers=4.1"

  - name: Create Backup Sub-Directory
    file:
      path: '/backups/{{ BACKUP }}'
      state: directory
      owner: steam
      group: steam
      mode: 0644

  - name: Get Option List
    uri:
      method: GET
      url: "{{ MORPHURL }}api/library/option-type-lists/{{ OPTIONLIST }}"
      headers:
        Authorization: "BEARER {{ MORPHTOKEN }}"
    register: OLDATA

  - name: Create TEMP File
    copy: 
      content: '{{ OLDATA.json.optionTypeList.initialDataset }}'
      dest: /json.txt
    when: BACKUP != "New"

  - name: Update Dataset
    json_patch:
      src: "/json.txt"
      operations:
        - op: add
          path: "/-"
          value: 
            name: "{{ BACKUP }}"
            value: "{{ BACKUP }}"
      pretty: yes
    when: BACKUP != "New"

  - name: Set File to Var
    shell: |
      cat /json.txt | jq tostring
    register: JSON
    when: BACKUP != "New"

  - name: Update Option List
    uri:
      method: PUT
      body_format: json
      url: "{{ MORPHURL }}api/library/option-type-lists/{{ OPTIONLIST }}"
      headers:
        Authorization: "BEARER {{ MORPHTOKEN }}"
      body: >
        {"optionTypeList": {"initialDataset": {{ JSON.stdout }}}}
      status_code: 200
    when: BACKUP != "New"

  - name: Delete TEMP File
    file:
      path: /json.txt
      state: absent
    when: BACKUP != "New"

  - name: Get Job Inventory
    uri:
      method: GET
      url: "{{ MORPHURL }}api/jobs/{{ JOB }}"
      headers:
        Authorization: "BEARER {{ MORPHTOKEN }}"
    register: JOBDATA

  - name: Create TEMP File
    copy: 
      content: '{{ JOBDATA.json.job.targets }}'
      dest: /json.txt

  - name: Update Dataset
    json_patch:
      src: "/json.txt"
      operations:
        - op: add
          path: "/-"
          force_integer: true
          value: 
            refId: '{{ INSTANCEID }}'
      pretty: yes
  
  - name: Set File to Var
    shell: |
      cat /json.txt | jq -c
    register: JSON

  - name: Update Job Inventory
    uri:
      method: PUT
      body_format: json
      url: "{{ MORPHURL }}api/jobs/{{ JOB }}"
      headers:
        Authorization: "BEARER {{ MORPHTOKEN }}"
      body: >
        {"job": {"targets": {{ JSON.stdout }}}}
      status_code: 200

  - name: Delete TEMP File
    file:
      path: /json.txt
      state: absent