---
  GAME_PATH: "{{ morpheus['customOptions']['gamePath'] }}"

  #SERVERID: '896660'
  SERVERID: "{{ morpheus['customOptions']['steamAppId'] }}"

  STEAMPORT: "{{ morpheus['customOptions']['steamPort'] }}"
  WORLD: "{{ morpheus['customOptions']['world'] }}"
  PASSWORD: "{{ morpheus['customOptions']['password'] }}"

  INSTANCEID: "{{ morpheus['instance']['id'] }}"