---
  METAVER: '1.11'
  METASOURCE: 'mmsource-1.11.0-git1148-linux.tar.gz'
  SOURCEMODSOURCE: 'sourcemod-1.11.0-git6923-linux.tar.gz'
  SOURCEMODVER: '1.11'

  SERVERID: '896660'

  STEAMPORT: "{{ morpheus['customOptions']['steamPort'] }}"
  WORLD: "{{ morpheus['customOptions']['world'] }}"
  PASSWORD: "{{ morpheus['customOptions']['password'] }}"

  BACKUP: "{{ morpheus['customOptions']['steamBackup'] }}"
  NEWBACKUP: "{{ morpheus['customOptions']['newSteamBackup'] }}"

  URL: "{{ morpheus['morpheus']['applianceUrl'] }}"
  TOKEN: "{{ morpheus['morpheus']['apiAccessToken'] }}"
  INSTANCEID: "{{ morpheus['instance']['id'] }}"