galaxy_info:
  role_name: wine
  author: Chris Bunge
  description: Installs WineHQ stable for running Windows game servers on Ubuntu
  company: Code the Things
  license: license (GPLv2, CC-BY, etc)
  min_ansible_version: 2.9
  github_branch: main
  platforms:
    - name: Ubuntu
      versions:
      - focal
      - bionic
      - jammy
      - noble
  galaxy_tags:
    - wine
    - steam
