---
- name: Create game install directory
  file:
    path: "{{ GAME_PATH }}"
    state: directory
    owner: steam
    group: steam
    mode: '0755'

- name: Install L4D2 Fake (Bug Related)
  shell:
    cmd: |
      /usr/games/steamcmd +force_install_dir '{{ GAME_PATH }}' +login anonymous +@sSteamCmdForcePlatformType windows +app_update {{ SERVERID }} -validate +quit
  become: true
  become_user: steam

- name: Install L4D2 Fix
  shell:
    cmd: |
      /usr/games/steamcmd +force_install_dir '{{ GAME_PATH }}' +login anonymous +@sSteamCmdForcePlatformType linux +app_update {{ SERVERID }} -validate +quit
  become: true
  become_user: steam

- name: Install Metamod and Sourcemod
  import_role:
    name: metamod

- name: Symlink Server Config
  file:
    src: /steam/morpheus/server.cfg
    dest: "{{ GAME_PATH }}/left4dead2/cfg/server.cfg"
    state: link
    owner: steam
    group: steam
    mode: 0644
    force: true

- name: Symlink MOTD Config
  file:
    src: /steam/morpheus/motd.txt
    dest: "{{ GAME_PATH }}/left4dead2/motd.txt"
    state: link
    owner: steam
    group: steam
    mode: 0644
    force: true

- name: Symlink Host Config
  file:
    src: /steam/morpheus/host.txt
    dest: "{{ GAME_PATH }}/left4dead2/host.txt"
    state: link
    owner: steam
    group: steam
    mode: 0644
    force: true

- name: Creating Start Script
  copy:
    dest: /steam/start.sh
    content: |
      {{ GAME_PATH }}/srcds_run -game left4dead2 +exec server.cfg +port {{ STEAMPORT }} +maxplayers 8 -tickrate 100 -pingboost 2 +map c1m1_hotel > /dev/null 2>&1 &
    mode: a+x

- name: Fix File Permissions
  file:
    path: /steam/
    owner: steam
    group: steam
    recurse: true

- name: Start Screen Session
  shell: |
    screen -dmS steam /steam/start.sh
