---
- name: Install L4D2
  shell:
    cmd: |
      steamcmd +login anonymous +force_install_dir '/steam/server' +app_update 222860 -validate +quit

- name: Install Metamod
  ansible.builtin.unarchive:
    src: https://mms.alliedmods.net/mmsdrop/{{ METAVER }}/{{ METASOURCE }}
    dest: /steam/server/left4dead2
    remote_src: yes

- name: Install Sourcemod
  ansible.builtin.unarchive:
    src: https://sm.alliedmods.net/smdrop/{{ SOURCEMODVER }}/{{ SOURCEMODSOURCE }}
    dest: /steam/server/left4dead2
    remote_src: yes

- name: Symlink Server Config
  file:
    src: /steam/morpheus/server.cfg
    dest: /steam/server/left4dead2/cfg/server.cfg
    state: link
    owner: steam
    group: steam
    mode: 0777

- name: Symlink Server Config
  file:
    src: /steam/morpheus/banned_user.cfg
    dest: /steam/server/left4dead2/cfg/banned_user.cfg
    state: link
    owner: steam
    group: steam
    mode: 0777

- name: Symlink Server Config
  file:
    src: /steam/morpheus/banned_ip.cfg
    dest: /steam/server/left4dead2/cfg/banned_ip.cfg
    state: link
    owner: steam
    group: steam
    mode: 0777

- name: Symlink Server Config
  file:
    src: /steam/morpheus/motd.txt
    dest: /steam/server/left4dead2/motd.txt
    state: link
    owner: steam
    group: steam
    mode: 0777
  
- name: Symlink Server Config
  file:
    src: /steam/morpheus/metamod.vdf
    dest: /steam/server/left4dead2/addons/metamod.vdf
    state: link
    owner: steam
    group: steam
    mode: 0777

- name: Symlink Server Config
  file:
    src: /steam/morpheus/host.txt
    dest: /steam/server/left4dead2/host.txt
    state: link
    owner: steam
    group: steam
    mode: 0777

- name: Symlink Server Config
  file:
    src: /steam/morpheus/admins_simple.ini
    dest: /steam/server/left4dead2/addons/sourcemod/configs/admins_simple.ini
    state: link
    owner: steam
    group: steam
    mode: 0777