---
  - name: Start L4D2 Server
    hosts: all
    gather_facts: true
    become: true
    become_user: steam
    
    vars:
      steamPort: "{{ morpheus['customOptions']['steamPort'] }}"

    tasks:
      - name: Start L4D2 Server
        shell:
          cmd: |
            /steam/server/srcds_run -game left4dead2 +exec server.cfg +port {{ steamPort }} +maxplayers 8 -tickrate 100 -pingboost 2 +map c1m1_hotel > /dev/null 2>&1 &