---
- name: Install Wine
  import_role:
    name: wine

- name: Install Enshrouded
  shell:
    cmd: |
      /usr/games/steamcmd +@ShutdownOnFailedCommand 0 +@sSteamCmdForcePlatformType windows +force_install_dir '{{ GAME_PATH }}' +login anonymous +app_update {{ SERVERID }} -validate +quit
  become: true
  become_user: steam

- name: Symlink Enshrouded Config
  file:
    src: /steam/morpheus/enshrouded_server.json
    dest: "{{ GAME_PATH }}/enshrouded_server.json"
    state: link
    owner: steam
    group: steam
    mode: 0644
    force: true

- name: Create start.sh file
  copy:
    content: |
      #!/bin/bash
      wine start {{ GAME_PATH }}/enshrouded_server.exe
    dest: /steam/start.sh
    mode: '0755'

- name: Fix File Permissions
  file:
    path: /steam/
    owner: steam
    group: steam
    recurse: true

- name: Start Screen Session
  shell: |
    screen -dmS steam /steam/start.sh
  become: true
  become_user: steam
