---
  GAME_PATH: "{{ morpheus['customOptions']['gamePath'] }}"

  GAMEVERSION: '0.10.0'

  #SERVERID: '4129620' # Windrose Dedicated Server
  SERVERID: "{{ morpheus['customOptions']['steamAppId'] }}"

  STEAMPORT: "{{ morpheus['customOptions']['steamPort'] }}"

  INSTANCEID: "{{ morpheus['instance']['id'] }}"

  WORLD: "{{ morpheus['customOptions']['world'] }}"