---
- name: Install Core Keeper
  shell:
    cmd: |
      /usr/games/steamcmd +@ShutdownOnFailedCommand 0 +@sSteamCmdForcePlatformType linux +force_install_dir '{{ GAME_PATH }}' +login anonymous +app_update {{ SERVERID }} -validate +quit
  become: true
  become_user: steam

- name: Creating Start Script
  copy:
    dest: /steam/start.sh
    content: |
      {{ GAME_PATH }}/_launch.sh
    mode: a+x

- name: Fix File Permissions
  file:
    path: /steam/
    owner: steam
    group: steam
    recurse: true

- name: Start Screen Session
  shell: |
    screen -dmS steam /steam/start.sh
